package upm.fis.practica.controller;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import spark.Request;
import spark.Response;
import upm.fis.andrea.Libro;
import upm.fis.practica.exceptions.RenderTemplateException;
import upm.fis.practica.model.aula.Aula;
import upm.fis.practica.model.aula.TAula;
import upm.fis.practica.model.usuario.observador.alumno.Alumno;
import upm.fis.practica.model.usuario.observador.pdi.Pdi;
import upm.fis.practica.peristencia.PAula;
import upm.fis.practica.view.VelocityRenderer;
import upm.fis.practica.view.ViewRenderer;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Gesti�nGR
//  @ File Name : CAulas.java
//  @ Date : 11/05/2022
//  @ Author : 
//
//




public class CAulas{
	
	private List<Aula> aulas;
	private ViewRenderer renderer;
	private PAula pAula;
	
	public CAulas( ) {
		pAula = new PAula();
		aulas = pAula.leerdearchivo();
		renderer = new VelocityRenderer();
	}

	public Aula cogeraula(String id){
		int index=0;
		for(int i=0;i<aulas.size();i++){
			if(aulas.get(i).getId().equals(id)){
				index = i;
			}
		}
		return aulas.get(index);
	}
	public int cogerindiceaula(String id){
		int index=0;
		for(int i=0;i<pAula.leerdearchivo().size();i++){
			if(pAula.leerdearchivo().get(i).getId().equals(id)){
				index = i;
			}
		}
		return index;
	}
	
	public String crearAula(Request request, Response response) {
		Map<String,Object> model = renderer.toModel(aulas, "aulas");
		String template = "crearaula.vm";

		try {
			return renderer.render(model, template);
		} catch (RenderTemplateException e) {
			e.printStackTrace();
		}
		return "";

	}
	public String mostrarAula(Request request, Response response){
		String id = request.queryParams("id");
		Map<String,Object> model = renderer.toModel(cogeraula(id));
		String template = "aula.vm";

		try {
			return renderer.render(model, template);
		} catch (RenderTemplateException e) {
			e.printStackTrace();
		}

		return "";
	}

	public String listarAulas(Request request, Response response) {

		Map<String,Object> model = renderer.toModel(aulas, "aulas");
		String template = "aulas.vm";

		try {
			return renderer.render(model, template);
		} catch (RenderTemplateException e) {
			e.printStackTrace();
		}

		return "";
	}
	public String guardaraulas(Request request, Response response) {
		String nombreaula = request.queryParams("nombreaula");
		String id = request.queryParams("id");
		double superficie = Double.parseDouble(request.queryParams("superficie"));
		int aforo = Integer.parseInt(request.queryParams("aforo"));
		TAula tipoAula = TAula.valueOf(request.queryParams("tipoAula"));
		Aula aula = new Aula(nombreaula, id, superficie, aforo, tipoAula);
		aulas.add(aula);
		pAula.pasarjsonaula(aulas);
		Map<String,Object> model = renderer.toModel(aulas, "aulas");
		String template = "guardaraula.vm";

		try {
			return renderer.render(model, template);
		} catch (RenderTemplateException e) {
			e.printStackTrace();
		}


		return "";
	}
	public String guardaryverAlumno(Request request, Response response, Alumno alumno){
		String id = request.queryParams("id");
		ArrayList<Aula> aulas =  this.pAula.leerdearchivo();
		aulas.get(cogerindiceaula(id)).getObservadores().add(alumno);
		pAula.pasarjsonaula(aulas);
		Map<String,Object> model = renderer.toModel(cogeraula(id));
		String template = "suscritobien.vm";

		try {
			return renderer.render(model, template);
		} catch (RenderTemplateException e) {
			e.printStackTrace();
		}

		return "";
	}
	public String guardaryverPdi(Request request, Response response, Pdi pdi){
		String id = request.queryParams("id");
		ArrayList<Aula> aulas =  this.pAula.leerdearchivo();
		aulas.get(cogerindiceaula(id)).getObservadores().add(pdi);
		pAula.pasarjsonaula(aulas);
		Map<String,Object> model = renderer.toModel(cogeraula(id));
		String template = "suscritobien.vm";

		try {
			return renderer.render(model, template);
		} catch (RenderTemplateException e) {
			e.printStackTrace();
		}

		return "";
	}

	public List<Aula> getAulas() {
		return pAula.leerdearchivo();
	}


}