package upm.fis.practica.controller;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Gesti�nGR
//  @ File Name : CUsuarios.java
//  @ Date : 11/05/2022
//  @ Author : 
//
//

import java.util.ArrayList;
import java.util.Map;

import spark.Request;
import spark.Response;
import upm.fis.practica.exceptions.RenderTemplateException;
import upm.fis.practica.view.VelocityRenderer;
import upm.fis.practica.view.ViewRenderer;

public class CUsuarios {
	private ViewRenderer renderer;
	private CAlumno cAlumno;
	private CPdi cPdi;
	private CPas cPas;

	public CUsuarios() {
		this.cAlumno = new CAlumno();
		this.cPdi = new CPdi();
		this.cPas = new CPas();
		this.renderer = new VelocityRenderer();
	}

	public String darAlta(Request request, Response response){
		Map<String,Object> model = renderer.toModel(new ArrayList<>(),"usuarios");
		String template = "altausuario.vm";
		try {
			return renderer.render(model, template);
		} catch (RenderTemplateException e) {
			e.printStackTrace();
		}
		return "";
	}

	public String darAltaAlumno(Request request, Response response){
		return cAlumno.darAltaAlumno(request,response);
	}
	public String darAltaPas(Request request, Response response){
		return cPas.darAltaPas(request,response);
	}
	public String darAltaPdi(Request request, Response response){
		return  cPdi.darAltaPdi(request,response);
	}

	public String guardarAlumno(Request request, Response response){
		return cAlumno.guardaralumno(request,response);
	}
	public String guardarPdi(Request request, Response response){
		return cPdi.guardarPdi(request, response);
	}
	public String guardarPas(Request request, Response response){
		return cPas.guardarpas(request,response);
	}

	public String listarAlumnos(Request request, Response response){
		return cAlumno.listarAlumnos(request,response);
	}
	public String listarPdis(Request request, Response response){
		return cPdi.listarpdis(request,response);
	}
	public String listarPas(Request request, Response response){
		return cPas.listarpas(request,response);
	}

	public String mostrarAlumno(Request request, Response response){ return cAlumno.mostrarAlumno(request,response); }
	public String mostrarPdi(Request request, Response response){
		return cPdi.moostrarPdi(request,response);
	}
	public String mostrarPas(Request request, Response response){
		return cPas.mostrarPas(request,response);
	}
}
