//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNF.DCJITRFPFProyectoIPS
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "DCJITRFPF_DSLProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DCJITRFPFProyectoIPS";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"DNF";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DCJITRFPFProyectoIPSDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCJITRFPFProyectoIPSCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DCJITRFPFProyectoIPSExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCJITRFPFProyectoIPSCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDCJITRFPFProyectoIPSExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DCJITRFPFProyectoIPSCommandSetId), 0x0001);
	
		// Package identifier
		public const string DCJITRFPFProyectoIPSPackageId = "5b9ef4f6-fde6-43d2-842c-f7a9f9572976";
		
		// Editor factory identifier
		public const string DCJITRFPFProyectoIPSEditorFactoryId = "62ada28a-7022-48ea-bc31-0d092625afd6";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DCJITRFPFProyectoIPSModelExplorerToolWindowId = "0a7cd275-81ee-47cb-89d3-470b3d111922";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace DNF.DCJITRFPFProyectoIPS
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DCJITRFPFProyectoIPSCommandSetId = "bcd3c796-0fb0-4db1-ae44-d1567d464e33";
	}
}