//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

[module: global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Scope = "type", Target = "DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDiagram")]

namespace DNF.DCJITRFPFProyectoIPS
{
	/// <summary>
	/// DomainClass DCJITRFPFProyectoIPSDiagram
	/// Description for DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDiagram
	/// </summary>
	[DslDesign::DisplayNameResource("DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDiagram.DisplayName", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDiagram.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainObjectId("be714e6a-34ba-4a2d-8e4a-dd52d40ff1e4")]
	public partial class DCJITRFPFProyectoIPSDiagram : DslDiagrams::Diagram
	{
		#region Diagram boilerplate
		private static DslDiagrams::StyleSet classStyleSet;
		private static global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields;
		/// <summary>
		/// Per-class style set for this shape.
		/// </summary>
		protected override DslDiagrams::StyleSet ClassStyleSet
		{
			get
			{
				if (classStyleSet == null)
				{
					classStyleSet = CreateClassStyleSet();
				}
				return classStyleSet;
			}
		}
		
		/// <summary>
		/// Per-class ShapeFields for this shape
		/// </summary>
		public override global::System.Collections.Generic.IList<DslDiagrams::ShapeField> ShapeFields
		{
			get
			{
				if (shapeFields == null)
				{
					shapeFields = CreateShapeFields();
				}
				return shapeFields;
			}
		}
		#endregion
		#region Toolbox filters
		private static global::System.ComponentModel.ToolboxItemFilterAttribute[] toolboxFilters = new global::System.ComponentModel.ToolboxItemFilterAttribute[] {
					new global::System.ComponentModel.ToolboxItemFilterAttribute(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSToolboxHelperBase.ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) };
		
		/// <summary>
		/// Toolbox item filter attributes for this diagram.
		/// </summary>
		public override global::System.Collections.ICollection TargetToolboxItemFilterAttributes
		{
			get
			{
				return toolboxFilters;
			}
		}
		#endregion
		#region Auto-placement
		/// <summary>
		/// Indicate that child shapes should added through view fixup should be placed automatically.
		/// </summary>
		public override bool ShouldAutoPlaceChildShapes
		{
			get
			{
				return true;
			}
		}
		#endregion
		#region Shape mapping
		/// <summary>
		/// Called during view fixup to ask the parent whether a shape should be created for the given child element.
		/// </summary>
		/// <remarks>
		/// Always return true, since we assume there is only one diagram per model file for DSL scenarios.
		/// </remarks>
		protected override bool ShouldAddShapeForElement(DslModeling::ModelElement element)
		{
			return true;
		}
		
		/// <summary>
		/// Called during view fixup to configure the given child element, after it has been created.
		/// </summary>
		/// <remarks>
		/// Custom code for choosing the shapes attached to either end of a connector is called from here.
		/// </remarks>
		protected override void OnChildConfiguring(DslDiagrams::ShapeElement child, bool createdDuringViewFixup)
		{
			DslDiagrams::NodeShape sourceShape;
			DslDiagrams::NodeShape targetShape;
			DslDiagrams::BinaryLinkShape connector = child as DslDiagrams::BinaryLinkShape;
			if(connector == null)
			{
				base.OnChildConfiguring(child, createdDuringViewFixup);
				return;
			}
			this.GetSourceAndTargetForConnector(connector, out sourceShape, out targetShape);
			
			global::System.Diagnostics.Debug.Assert(sourceShape != null && targetShape != null, "Unable to find source and target shapes for connector.");
			connector.Connect(sourceShape, targetShape);
		}
		
		/// <summary>
		/// helper method to find the shapes for either end of a connector, including calling the user's custom code
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
		internal void GetSourceAndTargetForConnector(DslDiagrams::BinaryLinkShape connector, out DslDiagrams::NodeShape sourceShape, out DslDiagrams::NodeShape targetShape)
		{
			sourceShape = null;
			targetShape = null;
			
			if (sourceShape == null || targetShape == null)
			{
				DslDiagrams::NodeShape[] endShapes = GetEndShapesForConnector(connector);
				if(sourceShape == null)
				{
					sourceShape = endShapes[0];
				}
				if(targetShape == null)
				{
					targetShape = endShapes[1];
				}
			}
		}
		
		/// <summary>
		/// Helper method to find shapes for either end of a connector by looking for shapes associated with either end of the relationship mapped to the connector.
		/// </summary>
		private DslDiagrams::NodeShape[] GetEndShapesForConnector(DslDiagrams::BinaryLinkShape connector)
		{
			DslModeling::ElementLink link = connector.ModelElement as DslModeling::ElementLink;
			DslDiagrams::NodeShape sourceShape = null, targetShape = null;
			if (link != null)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = link.LinkedElements;
				if (linkedElements.Count == 2)
				{
					DslDiagrams::Diagram currentDiagram = this.Diagram;
					DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							sourceShape = shape;
							break;
						}
					}
					
					presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
					foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
					{
						DslDiagrams::NodeShape shape = presentationElement as DslDiagrams::NodeShape;
						if (shape != null && shape.Diagram == currentDiagram)
						{
							targetShape = shape;
							break;
						}
					}
		
				}
			}
			
			return new DslDiagrams::NodeShape[] { sourceShape, targetShape };
		}
		
		/// <summary>
		/// Creates a new shape for the given model element as part of view fixup
		/// </summary>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily", Justification = "Generated code.")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
		protected override DslDiagrams::ShapeElement CreateChildShape(DslModeling::ModelElement element)
		{
			if(element is global::DNF.DCJITRFPFProyectoIPS.AtributoNM)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaAtributoNM newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaAtributoNM(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.ClavePrimaria)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaClavePrimaria newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaClavePrimaria(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.AtributoRelacion)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaAtributoRelacion newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaAtributoRelacion(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.Entidad)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaEntidad newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaEntidad(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.Relacion)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaRelacion newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaRelacion(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.EstiloPortalWeb)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaPortalWeb newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaPortalWeb(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.EstiloPaginaWeb)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaPaginaWeb newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaPaginaWeb(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.EstiloFormulario)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaFormulario newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaFormulario(this.Partition);
				if(newShape != null) newShape.Size = newShape.DefaultSize; // set default shape size
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.EntidadReferenciasAtributo)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaEntidadRefAtributo newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaEntidadRefAtributo(this.Partition);
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.PrimeraRelacionReferenciasEntidad)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaPrimeraRelacionEntidad newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaPrimeraRelacionEntidad(this.Partition);
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.SegundaRelacionReferenciasEntidad)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaSegundaRelacionEntidad newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaSegundaRelacionEntidad(this.Partition);
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.AtributoRelacionReferencesRelacion)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaRelacionRefAtributo newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaRelacionRefAtributo(this.Partition);
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.EntidadReferencesEstiloPaginaWeb)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaRelacionPaginaWebEntidad newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaRelacionPaginaWebEntidad(this.Partition);
				return newShape;
			}
			if(element is global::DNF.DCJITRFPFProyectoIPS.AtributoReferencesEstiloFormulario)
			{
				global::DNF.DCJITRFPFProyectoIPS.MetaforaRelacionFormularioAtributo newShape = new global::DNF.DCJITRFPFProyectoIPS.MetaforaRelacionFormularioAtributo(this.Partition);
				return newShape;
			}
			return base.CreateChildShape(element);
		}
		#endregion
		#region Decorator mapping
		/// <summary>
		/// Initialize shape decorator mappings.  This is done here rather than in individual shapes because decorator maps
		/// are defined per diagram type rather than per shape type.
		/// </summary>
		protected override void InitializeShapeFields(global::System.Collections.Generic.IList<DslDiagrams::ShapeField> shapeFields)
		{
			base.InitializeShapeFields(shapeFields);
			global::DNF.DCJITRFPFProyectoIPS.MetaforaEntidad.DecoratorsInitialized += MetaforaEntidadDecoratorMap.OnDecoratorsInitialized;
			global::DNF.DCJITRFPFProyectoIPS.MetaforaAtributoNM.DecoratorsInitialized += MetaforaAtributoNMDecoratorMap.OnDecoratorsInitialized;
			global::DNF.DCJITRFPFProyectoIPS.MetaforaClavePrimaria.DecoratorsInitialized += MetaforaClavePrimariaDecoratorMap.OnDecoratorsInitialized;
			global::DNF.DCJITRFPFProyectoIPS.MetaforaRelacion.DecoratorsInitialized += MetaforaRelacionDecoratorMap.OnDecoratorsInitialized;
			global::DNF.DCJITRFPFProyectoIPS.MetaforaPortalWeb.DecoratorsInitialized += MetaforaPortalWebDecoratorMap.OnDecoratorsInitialized;
			global::DNF.DCJITRFPFProyectoIPS.MetaforaPaginaWeb.DecoratorsInitialized += MetaforaPaginaWebDecoratorMap.OnDecoratorsInitialized;
			global::DNF.DCJITRFPFProyectoIPS.MetaforaFormulario.DecoratorsInitialized += MetaforaFormularioDecoratorMap.OnDecoratorsInitialized;
			global::DNF.DCJITRFPFProyectoIPS.MetaforaAtributoRelacion.DecoratorsInitialized += MetaforaAtributoRelacionDecoratorMap.OnDecoratorsInitialized;
			global::DNF.DCJITRFPFProyectoIPS.MetaforaPrimeraRelacionEntidad.DecoratorsInitialized += MetaforaPrimeraRelacionEntidadDecoratorMap.OnDecoratorsInitialized;
			global::DNF.DCJITRFPFProyectoIPS.MetaforaSegundaRelacionEntidad.DecoratorsInitialized += MetaforaSegundaRelacionEntidadDecoratorMap.OnDecoratorsInitialized;
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaEntidad.
		/// </summary>
		internal static partial class MetaforaEntidadDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaEntidad.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.Entidad.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Texto").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaAtributoNM.
		/// </summary>
		internal static partial class MetaforaAtributoNMDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaAtributoNM.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.Atributo.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Texto").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaClavePrimaria.
		/// </summary>
		internal static partial class MetaforaClavePrimariaDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaClavePrimaria.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.Atributo.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Texto").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaRelacion.
		/// </summary>
		internal static partial class MetaforaRelacionDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaRelacion.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.Relacion.nombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Texto").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaPortalWeb.
		/// </summary>
		internal static partial class MetaforaPortalWebDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaPortalWeb.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.EstiloPortalWeb.EstilosDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Estilo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaPaginaWeb.
		/// </summary>
		internal static partial class MetaforaPaginaWebDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaPaginaWeb.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.EstiloPaginaWeb.EstilosDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Estilo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaFormulario.
		/// </summary>
		internal static partial class MetaforaFormularioDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaFormulario.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.EstiloFormulario.EstilosDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Estilo").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaAtributoRelacion.
		/// </summary>
		internal static partial class MetaforaAtributoRelacionDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaAtributoRelacion.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.Atributo.NombreDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Texto").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaPrimeraRelacionEntidad.
		/// </summary>
		internal static partial class MetaforaPrimeraRelacionEntidadDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaPrimeraRelacionEntidad.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.PrimeraRelacionReferenciasEntidad.CardinalidadDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Card1").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		/// <summary>
		/// Class containing decorator path traversal methods for MetaforaSegundaRelacionEntidad.
		/// </summary>
		internal static partial class MetaforaSegundaRelacionEntidadDecoratorMap
		{
			/// <summary>
			/// Event handler called when decorator initialization is complete for MetaforaSegundaRelacionEntidad.  Adds decorator mappings for this shape or connector.
			/// </summary>
			public static void OnDecoratorsInitialized(object sender, global::System.EventArgs e)
			{
				DslDiagrams::ShapeElement shape = (DslDiagrams::ShapeElement)sender;
				DslDiagrams::AssociatedPropertyInfo propertyInfo;
				
				propertyInfo = new DslDiagrams::AssociatedPropertyInfo(global::DNF.DCJITRFPFProyectoIPS.SegundaRelacionReferenciasEntidad.CardinalidadDomainPropertyId);
				DslDiagrams::ShapeElement.FindDecorator(shape.Decorators, "Cardi1").AssociateValueWith(shape.Store, propertyInfo);
			}
		}
		
		#endregion
		
		#region Connect actions
		private bool changingMouseAction;
		private global::DNF.DCJITRFPFProyectoIPS.EntidadAtributoConexConnectAction entidadAtributoConexConnectAction;
		private global::DNF.DCJITRFPFProyectoIPS.PrimeraRelacionToolConnectAction primeraRelacionToolConnectAction;
		private global::DNF.DCJITRFPFProyectoIPS.SegundaRelacionToolConnectAction segundaRelacionToolConnectAction;
		private global::DNF.DCJITRFPFProyectoIPS.RelacionAtributoConexConnectAction relacionAtributoConexConnectAction;
		private global::DNF.DCJITRFPFProyectoIPS.PagWebRefEntidadConnectAction pagWebRefEntidadConnectAction;
		private global::DNF.DCJITRFPFProyectoIPS.AtributoRefFormularioConnectAction atributoRefFormularioConnectAction;
		/// <summary>
		/// Virtual method to provide a filter when to select the mouse action
		/// </summary>
		/// <param name="activeView">Currently active view</param>
		/// <param name="filter">filter string used to filter the toolbox items</param>
		protected virtual bool SelectedToolboxItemSupportsFilterString(DslDiagrams::DiagramView activeView, string filter)
		{
			return activeView.SelectedToolboxItemSupportsFilterString(filter);
		}
		/// <summary>
		/// Override to provide the right mouse action when trying
		/// to create links on the diagram
		/// </summary>
		/// <param name="pointArgs"></param>
		public override void OnViewMouseEnter(DslDiagrams::DiagramPointEventArgs pointArgs)
		{
			if (pointArgs  == null) throw new global::System.ArgumentNullException("pointArgs");
		
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
			if(activeView != null)
			{
				DslDiagrams::MouseAction action = null;
				if (SelectedToolboxItemSupportsFilterString(activeView, global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSToolboxHelper.EntidadAtributoConexFilterString))
				{
					if (this.entidadAtributoConexConnectAction == null)
					{
						this.entidadAtributoConexConnectAction = new global::DNF.DCJITRFPFProyectoIPS.EntidadAtributoConexConnectAction(this);
						this.entidadAtributoConexConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.entidadAtributoConexConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSToolboxHelper.PrimeraRelacionToolFilterString))
				{
					if (this.primeraRelacionToolConnectAction == null)
					{
						this.primeraRelacionToolConnectAction = new global::DNF.DCJITRFPFProyectoIPS.PrimeraRelacionToolConnectAction(this);
						this.primeraRelacionToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.primeraRelacionToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSToolboxHelper.SegundaRelacionToolFilterString))
				{
					if (this.segundaRelacionToolConnectAction == null)
					{
						this.segundaRelacionToolConnectAction = new global::DNF.DCJITRFPFProyectoIPS.SegundaRelacionToolConnectAction(this);
						this.segundaRelacionToolConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.segundaRelacionToolConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSToolboxHelper.RelacionAtributoConexFilterString))
				{
					if (this.relacionAtributoConexConnectAction == null)
					{
						this.relacionAtributoConexConnectAction = new global::DNF.DCJITRFPFProyectoIPS.RelacionAtributoConexConnectAction(this);
						this.relacionAtributoConexConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.relacionAtributoConexConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSToolboxHelper.PagWebRefEntidadFilterString))
				{
					if (this.pagWebRefEntidadConnectAction == null)
					{
						this.pagWebRefEntidadConnectAction = new global::DNF.DCJITRFPFProyectoIPS.PagWebRefEntidadConnectAction(this);
						this.pagWebRefEntidadConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.pagWebRefEntidadConnectAction;
				} 
				else if (SelectedToolboxItemSupportsFilterString(activeView, global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSToolboxHelper.AtributoRefFormularioFilterString))
				{
					if (this.atributoRefFormularioConnectAction == null)
					{
						this.atributoRefFormularioConnectAction = new global::DNF.DCJITRFPFProyectoIPS.AtributoRefFormularioConnectAction(this);
						this.atributoRefFormularioConnectAction.MouseActionDeactivated += new DslDiagrams::MouseAction.MouseActionDeactivatedEventHandler(OnConnectActionDeactivated);
					}
					action = this.atributoRefFormularioConnectAction;
				} 
				else
				{
					action = null;
				}
				
				if (pointArgs.DiagramClientView.ActiveMouseAction != action)
				{
					try
					{
						this.changingMouseAction = true;
						pointArgs.DiagramClientView.ActiveMouseAction = action;
					}
					finally
					{
						this.changingMouseAction = false;
					}
				}
			}
		}
		
		/// <summary>
		/// Snap toolbox selection back to regular pointer after using a custom connect action.
		/// </summary>
		private void OnConnectActionDeactivated(object sender, DslDiagrams::DiagramEventArgs e)
		{
			OnMouseActionDeactivated();
		}
		
		/// <summary>
		/// Overridable method to manage the mouse deactivation. The default implementation snap stoolbox selection back to regular pointer 
		/// after using a custom connect action.
		/// </summary>
		protected virtual void OnMouseActionDeactivated()
		{
			DslDiagrams::DiagramView activeView = this.ActiveDiagramView;
		
			if (activeView != null && activeView.Toolbox != null)
			{
				// If we're not changing mouse action due to changing toolbox selection change,
				// reset toolbox selection.
				if (!this.changingMouseAction)
				{
					activeView.Toolbox.SelectedToolboxItemUsed();
				}
			}
		}
		#endregion
		
		/// <summary>
		/// Dispose of connect actions.
		/// </summary>
		protected override void Dispose(bool disposing)
		{
			try
			{
				if(disposing)
				{
					if(this.entidadAtributoConexConnectAction != null)
					{
						this.entidadAtributoConexConnectAction.Dispose();
						this.entidadAtributoConexConnectAction = null;
					}
					if(this.primeraRelacionToolConnectAction != null)
					{
						this.primeraRelacionToolConnectAction.Dispose();
						this.primeraRelacionToolConnectAction = null;
					}
					if(this.segundaRelacionToolConnectAction != null)
					{
						this.segundaRelacionToolConnectAction.Dispose();
						this.segundaRelacionToolConnectAction = null;
					}
					if(this.relacionAtributoConexConnectAction != null)
					{
						this.relacionAtributoConexConnectAction.Dispose();
						this.relacionAtributoConexConnectAction = null;
					}
					if(this.pagWebRefEntidadConnectAction != null)
					{
						this.pagWebRefEntidadConnectAction.Dispose();
						this.pagWebRefEntidadConnectAction = null;
					}
					if(this.atributoRefFormularioConnectAction != null)
					{
						this.atributoRefFormularioConnectAction.Dispose();
						this.atributoRefFormularioConnectAction = null;
					}
				}
			}
			finally
			{
				base.Dispose(disposing);
			}
		}
		#region Constructors, domain class Id
	
		/// <summary>
		/// DCJITRFPFProyectoIPSDiagram domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xbe714e6a, 0x34ba, 0x4a2d, 0x8e, 0x4a, 0xdd, 0x52, 0xd4, 0x0f, 0xf1, 0xe4);
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DCJITRFPFProyectoIPSDiagram(DslModeling::Store store, params DslModeling::PropertyAssignment[] propertyAssignments)
			: this(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new element is to be created.</param>
		/// <param name="propertyAssignments">List of domain property id/value pairs to set once the element is created.</param>
		public DCJITRFPFProyectoIPSDiagram(DslModeling::Partition partition, params DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, propertyAssignments)
		{
		}
		#endregion
	}
}
namespace DNF.DCJITRFPFProyectoIPS
{
	
		/// <summary>
		/// Double derived implementation for the rule that initiates view fixup when an element that has an associated shape is added to the model.
		/// This now enables the DSL author to everride the SkipFixUp() method 
		/// </summary>
		internal partial class FixUpDiagramBase : DslModeling::AddRule
		{
			protected virtual bool SkipFixup(DslModeling::ModelElement childElement)
			{
				return childElement.IsDeleted;
			}
		}
	
		/// <summary>
		/// Rule that initiates view fixup when an element that has an associated shape is added to the model. 
		/// </summary>
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.AtributoNM), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.ClavePrimaria), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.AtributoRelacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.Entidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.Relacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.EstiloPortalWeb), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.EstiloPaginaWeb), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.EstiloFormulario), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddShapeParentExistRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.EntidadReferenciasAtributo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.PrimeraRelacionReferenciasEntidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.SegundaRelacionReferenciasEntidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.AtributoRelacionReferencesRelacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.EntidadReferencesEstiloPaginaWeb), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.AtributoReferencesEstiloFormulario), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed partial class FixUpDiagram : FixUpDiagramBase
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
			public override void ElementAdded(DslModeling::ElementAddedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
			
				DslModeling::ModelElement childElement = e.ModelElement;
				if (this.SkipFixup(childElement))
					return;
				DslModeling::ModelElement parentElement;
				if(childElement is DslModeling::ElementLink)
				{
					parentElement = GetParentForRelationship((DslModeling::ElementLink)childElement);
				} else
				if(childElement is global::DNF.DCJITRFPFProyectoIPS.AtributoNM)
				{
					parentElement = GetParentForAtributoNM((global::DNF.DCJITRFPFProyectoIPS.AtributoNM)childElement);
				} else
				if(childElement is global::DNF.DCJITRFPFProyectoIPS.ClavePrimaria)
				{
					parentElement = GetParentForClavePrimaria((global::DNF.DCJITRFPFProyectoIPS.ClavePrimaria)childElement);
				} else
				if(childElement is global::DNF.DCJITRFPFProyectoIPS.AtributoRelacion)
				{
					parentElement = GetParentForAtributoRelacion((global::DNF.DCJITRFPFProyectoIPS.AtributoRelacion)childElement);
				} else
				if(childElement is global::DNF.DCJITRFPFProyectoIPS.Entidad)
				{
					parentElement = GetParentForEntidad((global::DNF.DCJITRFPFProyectoIPS.Entidad)childElement);
				} else
				if(childElement is global::DNF.DCJITRFPFProyectoIPS.Relacion)
				{
					parentElement = GetParentForRelacion((global::DNF.DCJITRFPFProyectoIPS.Relacion)childElement);
				} else
				if(childElement is global::DNF.DCJITRFPFProyectoIPS.EstiloPortalWeb)
				{
					parentElement = GetParentForEstiloPortalWeb((global::DNF.DCJITRFPFProyectoIPS.EstiloPortalWeb)childElement);
				} else
				if(childElement is global::DNF.DCJITRFPFProyectoIPS.EstiloPaginaWeb)
				{
					parentElement = GetParentForEstiloPaginaWeb((global::DNF.DCJITRFPFProyectoIPS.EstiloPaginaWeb)childElement);
				} else
				if(childElement is global::DNF.DCJITRFPFProyectoIPS.EstiloFormulario)
				{
					parentElement = GetParentForEstiloFormulario((global::DNF.DCJITRFPFProyectoIPS.EstiloFormulario)childElement);
				} else
				{
					parentElement = null;
				}
				
				if(parentElement != null)
				{
					DslDiagrams::Diagram.FixUpDiagram(parentElement, childElement);
				}
			}
			public static global::DNF.DCJITRFPFProyectoIPS.TapizER GetParentForEntidad( global::DNF.DCJITRFPFProyectoIPS.Entidad root )
			{
				// Segments 0 and 1
				global::DNF.DCJITRFPFProyectoIPS.TapizER result = root.TapizER;
				if ( result == null ) return null;
				return result;
			}
			public static global::DNF.DCJITRFPFProyectoIPS.TapizER GetParentForAtributoNM( global::DNF.DCJITRFPFProyectoIPS.Atributo root )
			{
				// Segments 0 and 1
				global::DNF.DCJITRFPFProyectoIPS.TapizER result = root.TapizER;
				if ( result == null ) return null;
				return result;
			}
			public static global::DNF.DCJITRFPFProyectoIPS.TapizER GetParentForClavePrimaria( global::DNF.DCJITRFPFProyectoIPS.Atributo root )
			{
				// Segments 0 and 1
				global::DNF.DCJITRFPFProyectoIPS.TapizER result = root.TapizER;
				if ( result == null ) return null;
				return result;
			}
			public static global::DNF.DCJITRFPFProyectoIPS.TapizER GetParentForRelacion( global::DNF.DCJITRFPFProyectoIPS.Relacion root )
			{
				// Segments 0 and 1
				global::DNF.DCJITRFPFProyectoIPS.TapizER result = root.TapizER;
				if ( result == null ) return null;
				return result;
			}
			public static global::DNF.DCJITRFPFProyectoIPS.TapizER GetParentForEstiloPortalWeb( global::DNF.DCJITRFPFProyectoIPS.EstiloPortalWeb root )
			{
				// Segments 0 and 1
				global::DNF.DCJITRFPFProyectoIPS.TapizER result = root.TapizER;
				if ( result == null ) return null;
				return result;
			}
			public static global::DNF.DCJITRFPFProyectoIPS.TapizER GetParentForEstiloPaginaWeb( global::DNF.DCJITRFPFProyectoIPS.EstiloPaginaWeb root )
			{
				// Segments 0 and 1
				global::DNF.DCJITRFPFProyectoIPS.TapizER result = root.TapizER;
				if ( result == null ) return null;
				return result;
			}
			public static global::DNF.DCJITRFPFProyectoIPS.TapizER GetParentForEstiloFormulario( global::DNF.DCJITRFPFProyectoIPS.EstiloFormulario root )
			{
				// Segments 0 and 1
				global::DNF.DCJITRFPFProyectoIPS.TapizER result = root.TapizER;
				if ( result == null ) return null;
				return result;
			}
			public static global::DNF.DCJITRFPFProyectoIPS.TapizER GetParentForAtributoRelacion( global::DNF.DCJITRFPFProyectoIPS.Atributo root )
			{
				// Segments 0 and 1
				global::DNF.DCJITRFPFProyectoIPS.TapizER result = root.TapizER;
				if ( result == null ) return null;
				return result;
			}
			private static DslModeling::ModelElement GetParentForRelationship(DslModeling::ElementLink elementLink)
			{
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslModeling::ModelElement> linkedElements = elementLink.LinkedElements;
	
				if (linkedElements.Count == 2)
				{
					DslDiagrams::ShapeElement sourceShape = linkedElements[0] as DslDiagrams::ShapeElement;
					DslDiagrams::ShapeElement targetShape = linkedElements[1] as DslDiagrams::ShapeElement;
	
					if(sourceShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[0]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								sourceShape = shape;
								break;
							}
						}
					}
					
					if(targetShape == null)
					{
						DslModeling::LinkedElementCollection<DslDiagrams::PresentationElement> presentationElements = DslDiagrams::PresentationViewsSubject.GetPresentation(linkedElements[1]);
						foreach (DslDiagrams::PresentationElement presentationElement in presentationElements)
						{
							DslDiagrams::ShapeElement shape = presentationElement as DslDiagrams::ShapeElement;
							if (shape != null)
							{
								targetShape = shape;
								break;
							}
						}
					}
					
					if(sourceShape == null || targetShape == null)
					{
						global::System.Diagnostics.Debug.Fail("Unable to find source and/or target shape for view fixup.");
						return null;
					}
	
					DslDiagrams::ShapeElement sourceParent = sourceShape.ParentShape;
					DslDiagrams::ShapeElement targetParent = targetShape.ParentShape;
	
					while (sourceParent != targetParent && sourceParent != null)
					{
						DslDiagrams::ShapeElement curParent = targetParent;
						while (sourceParent != curParent && curParent != null)
						{
							curParent = curParent.ParentShape;
						}
	
						if(sourceParent == curParent)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					while (sourceParent != null)
					{
						// ensure that the parent can parent connectors (i.e., a diagram or a swimlane).
						if(sourceParent is DslDiagrams::Diagram || sourceParent is DslDiagrams::SwimlaneShape)
						{
							break;
						}
						else
						{
							sourceParent = sourceParent.ParentShape;
						}
					}
	
					global::System.Diagnostics.Debug.Assert(sourceParent != null && sourceParent.ModelElement != null, "Unable to find common parent for view fixup.");
					return sourceParent.ModelElement;
				}
	
				return null;
			}
		}
		
	
		/// <summary>
		/// A rule which fires when data mapped to outer text decorators has changed,
		/// so we can update the decorator host's bounds.
		/// </summary>
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.PrimeraRelacionReferenciasEntidad), InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.SegundaRelacionReferenciasEntidad), InitiallyDisabled=true)]
		internal sealed class DecoratorPropertyChanged : DslModeling::ChangeRule
		{
			[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity", Justification = "Generated code.")]
			public override void ElementPropertyChanged(DslModeling::ElementPropertyChangedEventArgs e)
			{
				if(e == null) throw new global::System.ArgumentNullException("e");
				
				if (e.DomainProperty.Id == global::DNF.DCJITRFPFProyectoIPS.PrimeraRelacionReferenciasEntidad.CardinalidadDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::DNF.DCJITRFPFProyectoIPS.MetaforaPrimeraRelacionEntidad.FindMetaforaPrimeraRelacionEntidadDecorator("Card1");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::DNF.DCJITRFPFProyectoIPS.PrimeraRelacionReferenciasEntidad.DomainClassId);
					}
				}
				else if (e.DomainProperty.Id == global::DNF.DCJITRFPFProyectoIPS.SegundaRelacionReferenciasEntidad.CardinalidadDomainPropertyId)
				{
					DslDiagrams::Decorator decorator = global::DNF.DCJITRFPFProyectoIPS.MetaforaSegundaRelacionEntidad.FindMetaforaSegundaRelacionEntidadDecorator("Cardi1");
					if(decorator != null)
					{
						decorator.UpdateDecoratorHostShapes(e.ModelElement, global::DNF.DCJITRFPFProyectoIPS.SegundaRelacionReferenciasEntidad.DomainClassId);
					}
				}
			}
		}
	
		/// <summary>
		/// Reroute a connector when the role players of its underlying relationship change
		/// </summary>
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.EntidadReferenciasAtributo), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.PrimeraRelacionReferenciasEntidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.SegundaRelacionReferenciasEntidad), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.AtributoRelacionReferencesRelacion), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.EntidadReferencesEstiloPaginaWeb), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		[DslModeling::RuleOn(typeof(global::DNF.DCJITRFPFProyectoIPS.AtributoReferencesEstiloFormulario), FireTime = DslModeling::TimeToFire.TopLevelCommit, Priority = DslDiagrams::DiagramFixupConstants.AddConnectionRulePriority, InitiallyDisabled=true)]
		internal sealed class ConnectorRolePlayerChanged : DslModeling::RolePlayerChangeRule
		{
			/// <summary>
			/// Reroute a connector when the role players of its underlying relationship change
			/// </summary>
			public override void RolePlayerChanged(DslModeling::RolePlayerChangedEventArgs e)
			{
				if (e == null) throw new global::System.ArgumentNullException("e");
	
				global::System.Collections.ObjectModel.ReadOnlyCollection<DslDiagrams::PresentationViewsSubject> connectorLinks = DslDiagrams::PresentationViewsSubject.GetLinksToPresentation(e.ElementLink);
				foreach (DslDiagrams::PresentationViewsSubject connectorLink in connectorLinks)
				{
					// Fix up any binary link shapes attached to the element link.
					DslDiagrams::BinaryLinkShape linkShape = connectorLink.Presentation as DslDiagrams::BinaryLinkShape;
					if (linkShape != null)
					{
						global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDiagram diagram = linkShape.Diagram as global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDiagram;
						if (diagram != null)
						{
							if (e.NewRolePlayer != null)
							{
								DslDiagrams::NodeShape fromShape;
								DslDiagrams::NodeShape toShape;
								diagram.GetSourceAndTargetForConnector(linkShape, out fromShape, out toShape);
								if (fromShape != null && toShape != null)
								{
									if (!object.Equals(fromShape, linkShape.FromShape))
									{
										linkShape.FromShape = fromShape;
									}
									if (!object.Equals(linkShape.ToShape, toShape))
									{
										linkShape.ToShape = toShape;
									}
								}
								else
								{
									// delete the connector if we cannot find an appropriate target shape.
									linkShape.Delete();
								}
							}
							else
							{
								// delete the connector if the new role player is null.
								linkShape.Delete();
							}
						}
					}
				}
			}
		}
	}
