//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace DNF.DCJITRFPFProyectoIPS
{
	/// <summary>
	/// DomainModel DCJITRFPFProyectoIPSDomainModel
	/// Description for DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS
	/// </summary>
	[DslDesign::DisplayNameResource("DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel.DisplayName", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("3b42f749-f860-4245-85ed-46806663e597")]
	public partial class DCJITRFPFProyectoIPSDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DCJITRFPFProyectoIPSDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0x3b42f749, 0xf860, 0x4245, 0x85, 0xed, 0x46, 0x80, 0x66, 0x63, 0xe5, 0x97);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DCJITRFPFProyectoIPSDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(TapizER),
				typeof(Entidad),
				typeof(Atributo),
				typeof(AtributoNM),
				typeof(ClavePrimaria),
				typeof(Relacion),
				typeof(EstiloPortalWeb),
				typeof(EstiloPaginaWeb),
				typeof(EstiloFormulario),
				typeof(AtributoRelacion),
				typeof(TapizERTieneEntidad),
				typeof(TapizERTieneAtributo),
				typeof(EntidadReferenciasAtributo),
				typeof(TapizERTieneRelacion),
				typeof(PrimeraRelacionReferenciasEntidad),
				typeof(SegundaRelacionReferenciasEntidad),
				typeof(TapizERTieneEstiloPortalWeb),
				typeof(TapizERTieneEstiloPaginaWeb),
				typeof(TapizERHasEstiloFormulario),
				typeof(AtributoRelacionReferencesRelacion),
				typeof(EntidadReferencesEstiloPaginaWeb),
				typeof(AtributoReferencesEstiloFormulario),
				typeof(DCJITRFPFProyectoIPSDiagram),
				typeof(MetaforaEntidadRefAtributo),
				typeof(MetaforaPrimeraRelacionEntidad),
				typeof(MetaforaSegundaRelacionEntidad),
				typeof(MetaforaRelacionRefAtributo),
				typeof(MetaforaRelacionPaginaWebEntidad),
				typeof(MetaforaRelacionFormularioAtributo),
				typeof(MetaforaEntidad),
				typeof(MetaforaAtributoNM),
				typeof(MetaforaClavePrimaria),
				typeof(MetaforaRelacion),
				typeof(MetaforaPortalWeb),
				typeof(MetaforaPaginaWeb),
				typeof(MetaforaFormulario),
				typeof(MetaforaAtributoRelacion),
				typeof(global::DNF.DCJITRFPFProyectoIPS.FixUpDiagram),
				typeof(global::DNF.DCJITRFPFProyectoIPS.DecoratorPropertyChanged),
				typeof(global::DNF.DCJITRFPFProyectoIPS.ConnectorRolePlayerChanged),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(TapizER), "solucionER", TapizER.solucionERDomainPropertyId, typeof(TapizER.solucionERPropertyHandler)),
				new DomainMemberInfo(typeof(Entidad), "Nombre", Entidad.NombreDomainPropertyId, typeof(Entidad.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "Nombre", Atributo.NombreDomainPropertyId, typeof(Atributo.NombrePropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "tipoDato", Atributo.tipoDatoDomainPropertyId, typeof(Atributo.tipoDatoPropertyHandler)),
				new DomainMemberInfo(typeof(Atributo), "longitud", Atributo.longitudDomainPropertyId, typeof(Atributo.longitudPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoNM), "AdmiteRepetidos", AtributoNM.AdmiteRepetidosDomainPropertyId, typeof(AtributoNM.AdmiteRepetidosPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoNM), "AdmiteNoNulos", AtributoNM.AdmiteNoNulosDomainPropertyId, typeof(AtributoNM.AdmiteNoNulosPropertyHandler)),
				new DomainMemberInfo(typeof(Relacion), "nombre", Relacion.nombreDomainPropertyId, typeof(Relacion.nombrePropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortalWeb), "Estilos", EstiloPortalWeb.EstilosDomainPropertyId, typeof(EstiloPortalWeb.EstilosPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortalWeb), "Titulo", EstiloPortalWeb.TituloDomainPropertyId, typeof(EstiloPortalWeb.TituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortalWeb), "ColorTitulo", EstiloPortalWeb.ColorTituloDomainPropertyId, typeof(EstiloPortalWeb.ColorTituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortalWeb), "ColorFondo", EstiloPortalWeb.ColorFondoDomainPropertyId, typeof(EstiloPortalWeb.ColorFondoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortalWeb), "TamañoTitulo", EstiloPortalWeb.TamañoTituloDomainPropertyId, typeof(EstiloPortalWeb.TamañoTituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortalWeb), "AlineacionTitulo", EstiloPortalWeb.AlineacionTituloDomainPropertyId, typeof(EstiloPortalWeb.AlineacionTituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPortalWeb), "TipoLetraTitulo", EstiloPortalWeb.TipoLetraTituloDomainPropertyId, typeof(EstiloPortalWeb.TipoLetraTituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPaginaWeb), "Estilos", EstiloPaginaWeb.EstilosDomainPropertyId, typeof(EstiloPaginaWeb.EstilosPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPaginaWeb), "ColorTitulo", EstiloPaginaWeb.ColorTituloDomainPropertyId, typeof(EstiloPaginaWeb.ColorTituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPaginaWeb), "TamañoTitulo", EstiloPaginaWeb.TamañoTituloDomainPropertyId, typeof(EstiloPaginaWeb.TamañoTituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPaginaWeb), "AlineacionTitulo", EstiloPaginaWeb.AlineacionTituloDomainPropertyId, typeof(EstiloPaginaWeb.AlineacionTituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloPaginaWeb), "TipoLetraTitulo", EstiloPaginaWeb.TipoLetraTituloDomainPropertyId, typeof(EstiloPaginaWeb.TipoLetraTituloPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloFormulario), "Estilos", EstiloFormulario.EstilosDomainPropertyId, typeof(EstiloFormulario.EstilosPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloFormulario), "ColorFormulario", EstiloFormulario.ColorFormularioDomainPropertyId, typeof(EstiloFormulario.ColorFormularioPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloFormulario), "TamañoFormulario", EstiloFormulario.TamañoFormularioDomainPropertyId, typeof(EstiloFormulario.TamañoFormularioPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloFormulario), "AlineacionFormulario", EstiloFormulario.AlineacionFormularioDomainPropertyId, typeof(EstiloFormulario.AlineacionFormularioPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloFormulario), "TipoLetraCampo", EstiloFormulario.TipoLetraCampoDomainPropertyId, typeof(EstiloFormulario.TipoLetraCampoPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloFormulario), "FormatosVisualizacion", EstiloFormulario.FormatosVisualizacionDomainPropertyId, typeof(EstiloFormulario.FormatosVisualizacionPropertyHandler)),
				new DomainMemberInfo(typeof(EstiloFormulario), "TipoAtributo", EstiloFormulario.TipoAtributoDomainPropertyId, typeof(EstiloFormulario.TipoAtributoPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoRelacion), "AdmiteRepetidos", AtributoRelacion.AdmiteRepetidosDomainPropertyId, typeof(AtributoRelacion.AdmiteRepetidosPropertyHandler)),
				new DomainMemberInfo(typeof(AtributoRelacion), "AdmiteNoNulos", AtributoRelacion.AdmiteNoNulosDomainPropertyId, typeof(AtributoRelacion.AdmiteNoNulosPropertyHandler)),
				new DomainMemberInfo(typeof(PrimeraRelacionReferenciasEntidad), "Cardinalidad", PrimeraRelacionReferenciasEntidad.CardinalidadDomainPropertyId, typeof(PrimeraRelacionReferenciasEntidad.CardinalidadPropertyHandler)),
				new DomainMemberInfo(typeof(SegundaRelacionReferenciasEntidad), "Cardinalidad", SegundaRelacionReferenciasEntidad.CardinalidadDomainPropertyId, typeof(SegundaRelacionReferenciasEntidad.CardinalidadPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(TapizERTieneEntidad), "TapizER", TapizERTieneEntidad.TapizERDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERTieneEntidad), "Entidad", TapizERTieneEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERTieneAtributo), "TapizER", TapizERTieneAtributo.TapizERDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERTieneAtributo), "Atributo", TapizERTieneAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferenciasAtributo), "Entidad", EntidadReferenciasAtributo.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferenciasAtributo), "Atributo", EntidadReferenciasAtributo.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERTieneRelacion), "TapizER", TapizERTieneRelacion.TapizERDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERTieneRelacion), "Relacion", TapizERTieneRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(PrimeraRelacionReferenciasEntidad), "Relacion", PrimeraRelacionReferenciasEntidad.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(PrimeraRelacionReferenciasEntidad), "Entidad", PrimeraRelacionReferenciasEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(SegundaRelacionReferenciasEntidad), "Relacion", SegundaRelacionReferenciasEntidad.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(SegundaRelacionReferenciasEntidad), "Entidad", SegundaRelacionReferenciasEntidad.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERTieneEstiloPortalWeb), "TapizER", TapizERTieneEstiloPortalWeb.TapizERDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERTieneEstiloPortalWeb), "EstiloPortalWeb", TapizERTieneEstiloPortalWeb.EstiloPortalWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERTieneEstiloPaginaWeb), "TapizER", TapizERTieneEstiloPaginaWeb.TapizERDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERTieneEstiloPaginaWeb), "EstiloPaginaWeb", TapizERTieneEstiloPaginaWeb.EstiloPaginaWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERHasEstiloFormulario), "TapizER", TapizERHasEstiloFormulario.TapizERDomainRoleId),
				new DomainRolePlayerInfo(typeof(TapizERHasEstiloFormulario), "EstiloFormulario", TapizERHasEstiloFormulario.EstiloFormularioDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoRelacionReferencesRelacion), "AtributoRelacion", AtributoRelacionReferencesRelacion.AtributoRelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoRelacionReferencesRelacion), "Relacion", AtributoRelacionReferencesRelacion.RelacionDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesEstiloPaginaWeb), "Entidad", EntidadReferencesEstiloPaginaWeb.EntidadDomainRoleId),
				new DomainRolePlayerInfo(typeof(EntidadReferencesEstiloPaginaWeb), "EstiloPaginaWeb", EntidadReferencesEstiloPaginaWeb.EstiloPaginaWebDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoReferencesEstiloFormulario), "Atributo", AtributoReferencesEstiloFormulario.AtributoDomainRoleId),
				new DomainRolePlayerInfo(typeof(AtributoReferencesEstiloFormulario), "EstiloFormulario", AtributoReferencesEstiloFormulario.EstiloFormularioDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(25);
				createElementMap.Add(typeof(TapizER), 0);
				createElementMap.Add(typeof(Entidad), 1);
				createElementMap.Add(typeof(AtributoNM), 2);
				createElementMap.Add(typeof(ClavePrimaria), 3);
				createElementMap.Add(typeof(Relacion), 4);
				createElementMap.Add(typeof(EstiloPortalWeb), 5);
				createElementMap.Add(typeof(EstiloPaginaWeb), 6);
				createElementMap.Add(typeof(EstiloFormulario), 7);
				createElementMap.Add(typeof(AtributoRelacion), 8);
				createElementMap.Add(typeof(DCJITRFPFProyectoIPSDiagram), 9);
				createElementMap.Add(typeof(MetaforaEntidadRefAtributo), 10);
				createElementMap.Add(typeof(MetaforaPrimeraRelacionEntidad), 11);
				createElementMap.Add(typeof(MetaforaSegundaRelacionEntidad), 12);
				createElementMap.Add(typeof(MetaforaRelacionRefAtributo), 13);
				createElementMap.Add(typeof(MetaforaRelacionPaginaWebEntidad), 14);
				createElementMap.Add(typeof(MetaforaRelacionFormularioAtributo), 15);
				createElementMap.Add(typeof(MetaforaEntidad), 16);
				createElementMap.Add(typeof(MetaforaAtributoNM), 17);
				createElementMap.Add(typeof(MetaforaClavePrimaria), 18);
				createElementMap.Add(typeof(MetaforaRelacion), 19);
				createElementMap.Add(typeof(MetaforaPortalWeb), 20);
				createElementMap.Add(typeof(MetaforaPaginaWeb), 21);
				createElementMap.Add(typeof(MetaforaFormulario), 22);
				createElementMap.Add(typeof(MetaforaAtributoRelacion), 23);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new TapizER(partition, propertyAssignments);
				case 1: return new Entidad(partition, propertyAssignments);
				case 2: return new AtributoNM(partition, propertyAssignments);
				case 3: return new ClavePrimaria(partition, propertyAssignments);
				case 4: return new Relacion(partition, propertyAssignments);
				case 5: return new EstiloPortalWeb(partition, propertyAssignments);
				case 6: return new EstiloPaginaWeb(partition, propertyAssignments);
				case 7: return new EstiloFormulario(partition, propertyAssignments);
				case 8: return new AtributoRelacion(partition, propertyAssignments);
				case 9: return new DCJITRFPFProyectoIPSDiagram(partition, propertyAssignments);
				case 10: return new MetaforaEntidadRefAtributo(partition, propertyAssignments);
				case 11: return new MetaforaPrimeraRelacionEntidad(partition, propertyAssignments);
				case 12: return new MetaforaSegundaRelacionEntidad(partition, propertyAssignments);
				case 13: return new MetaforaRelacionRefAtributo(partition, propertyAssignments);
				case 14: return new MetaforaRelacionPaginaWebEntidad(partition, propertyAssignments);
				case 15: return new MetaforaRelacionFormularioAtributo(partition, propertyAssignments);
				case 16: return new MetaforaEntidad(partition, propertyAssignments);
				case 17: return new MetaforaAtributoNM(partition, propertyAssignments);
				case 18: return new MetaforaClavePrimaria(partition, propertyAssignments);
				case 19: return new MetaforaRelacion(partition, propertyAssignments);
				case 20: return new MetaforaPortalWeb(partition, propertyAssignments);
				case 21: return new MetaforaPaginaWeb(partition, propertyAssignments);
				case 22: return new MetaforaFormulario(partition, propertyAssignments);
				case 23: return new MetaforaAtributoRelacion(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(12);
				createElementLinkMap.Add(typeof(TapizERTieneEntidad), 0);
				createElementLinkMap.Add(typeof(TapizERTieneAtributo), 1);
				createElementLinkMap.Add(typeof(EntidadReferenciasAtributo), 2);
				createElementLinkMap.Add(typeof(TapizERTieneRelacion), 3);
				createElementLinkMap.Add(typeof(PrimeraRelacionReferenciasEntidad), 4);
				createElementLinkMap.Add(typeof(SegundaRelacionReferenciasEntidad), 5);
				createElementLinkMap.Add(typeof(TapizERTieneEstiloPortalWeb), 6);
				createElementLinkMap.Add(typeof(TapizERTieneEstiloPaginaWeb), 7);
				createElementLinkMap.Add(typeof(TapizERHasEstiloFormulario), 8);
				createElementLinkMap.Add(typeof(AtributoRelacionReferencesRelacion), 9);
				createElementLinkMap.Add(typeof(EntidadReferencesEstiloPaginaWeb), 10);
				createElementLinkMap.Add(typeof(AtributoReferencesEstiloFormulario), 11);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new TapizERTieneEntidad(partition, roleAssignments, propertyAssignments);
				case 1: return new TapizERTieneAtributo(partition, roleAssignments, propertyAssignments);
				case 2: return new EntidadReferenciasAtributo(partition, roleAssignments, propertyAssignments);
				case 3: return new TapizERTieneRelacion(partition, roleAssignments, propertyAssignments);
				case 4: return new PrimeraRelacionReferenciasEntidad(partition, roleAssignments, propertyAssignments);
				case 5: return new SegundaRelacionReferenciasEntidad(partition, roleAssignments, propertyAssignments);
				case 6: return new TapizERTieneEstiloPortalWeb(partition, roleAssignments, propertyAssignments);
				case 7: return new TapizERTieneEstiloPaginaWeb(partition, roleAssignments, propertyAssignments);
				case 8: return new TapizERHasEstiloFormulario(partition, roleAssignments, propertyAssignments);
				case 9: return new AtributoRelacionReferencesRelacion(partition, roleAssignments, propertyAssignments);
				case 10: return new EntidadReferencesEstiloPaginaWeb(partition, roleAssignments, propertyAssignments);
				case 11: return new AtributoReferencesEstiloFormulario(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DCJITRFPFProyectoIPSDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DCJITRFPFProyectoIPSDomainModel.resourceManager == null)
				{
					DCJITRFPFProyectoIPSDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DCJITRFPFProyectoIPSDomainModel).Assembly);
				}
				return DCJITRFPFProyectoIPSDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DCJITRFPFProyectoIPSDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DCJITRFPFProyectoIPSDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DCJITRFPFProyectoIPSDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DCJITRFPFProyectoIPSCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DCJITRFPFProyectoIPSDomainModel.copyClosure = copyFilter;
				}
				return DCJITRFPFProyectoIPSDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DCJITRFPFProyectoIPSDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DCJITRFPFProyectoIPSDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DCJITRFPFProyectoIPSDomainModel.removeClosure = removeFilter;
				}
				return DCJITRFPFProyectoIPSDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::DNF.DCJITRFPFProyectoIPS.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::DNF.DCJITRFPFProyectoIPS.DecoratorPropertyChanged));
			ruleManager.EnableRule(typeof(global::DNF.DCJITRFPFProyectoIPS.ConnectorRolePlayerChanged));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::DNF.DCJITRFPFProyectoIPS.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::DNF.DCJITRFPFProyectoIPS.DecoratorPropertyChanged));
			ruleManager.DisableRule(typeof(global::DNF.DCJITRFPFProyectoIPS.ConnectorRolePlayerChanged));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DCJITRFPFProyectoIPSDeleteClosure : DCJITRFPFProyectoIPSDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DCJITRFPFProyectoIPSDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DCJITRFPFProyectoIPSDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DCJITRFPFProyectoIPSDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::DNF.DCJITRFPFProyectoIPS.TapizERTieneEntidad.EntidadDomainRoleId, true);
			DomainRoles.Add(global::DNF.DCJITRFPFProyectoIPS.TapizERTieneAtributo.AtributoDomainRoleId, true);
			DomainRoles.Add(global::DNF.DCJITRFPFProyectoIPS.TapizERTieneRelacion.RelacionDomainRoleId, true);
			DomainRoles.Add(global::DNF.DCJITRFPFProyectoIPS.TapizERTieneEstiloPortalWeb.EstiloPortalWebDomainRoleId, true);
			DomainRoles.Add(global::DNF.DCJITRFPFProyectoIPS.TapizERTieneEstiloPaginaWeb.EstiloPaginaWebDomainRoleId, true);
			DomainRoles.Add(global::DNF.DCJITRFPFProyectoIPS.TapizERHasEstiloFormulario.EstiloFormularioDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DCJITRFPFProyectoIPSCopyClosure : DCJITRFPFProyectoIPSCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DCJITRFPFProyectoIPSCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DCJITRFPFProyectoIPSCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DCJITRFPFProyectoIPSCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace DNF.DCJITRFPFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: FormatosVisualizacion
	/// Description for DNF.DCJITRFPFProyectoIPS.FormatosVisualizacion
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum FormatosVisualizacion
	{
		/// <summary>
		/// AreaTexto
		/// Description for DNF.DCJITRFPFProyectoIPS.FormatosVisualizacion.AreaTexto
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.FormatosVisualizacion/AreaTexto.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		AreaTexto,
		/// <summary>
		/// Checkbox
		/// Description for DNF.DCJITRFPFProyectoIPS.FormatosVisualizacion.Checkbox
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.FormatosVisualizacion/Checkbox.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		Checkbox,
		/// <summary>
		/// RadioButton
		/// Description for DNF.DCJITRFPFProyectoIPS.FormatosVisualizacion.RadioButton
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.FormatosVisualizacion/RadioButton.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		RadioButton,
		/// <summary>
		/// ListaDesplegable
		/// Description for DNF.DCJITRFPFProyectoIPS.FormatosVisualizacion.ListaDesplegable
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.FormatosVisualizacion/ListaDesplegable.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		ListaDesplegable,
	}
}
namespace DNF.DCJITRFPFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: TipoAtributo
	/// Description for DNF.DCJITRFPFProyectoIPS.TipoAtributo
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum TipoAtributo
	{
		/// <summary>
		/// Entero
		/// Description for DNF.DCJITRFPFProyectoIPS.TipoAtributo.Entero
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.TipoAtributo/Entero.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		Entero = 0,
		/// <summary>
		/// Real
		/// Description for DNF.DCJITRFPFProyectoIPS.TipoAtributo.Real
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.TipoAtributo/Real.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		Real = 1,
		/// <summary>
		/// Fecha
		/// Description for DNF.DCJITRFPFProyectoIPS.TipoAtributo.Fecha
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.TipoAtributo/Fecha.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		Fecha = 3,
		/// <summary>
		/// Alfanumerico
		/// Description for DNF.DCJITRFPFProyectoIPS.TipoAtributo.Alfanumerico
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.TipoAtributo/Alfanumerico.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		Alfanumerico = 2,
	}
}
namespace DNF.DCJITRFPFProyectoIPS
{
	/// <summary>
	/// DomainEnumeration: Cardinalidades
	/// Description for DNF.DCJITRFPFProyectoIPS.Cardinalidades
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Cardinalidades
	{
		/// <summary>
		/// CeroUno
		/// Description for DNF.DCJITRFPFProyectoIPS.Cardinalidades.CeroUno
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.Cardinalidades/CeroUno.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		CeroUno = 0,
		/// <summary>
		/// UnoUno
		/// Description for DNF.DCJITRFPFProyectoIPS.Cardinalidades.UnoUno
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.Cardinalidades/UnoUno.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		UnoUno = 1,
		/// <summary>
		/// CeroMuchos
		/// Description for DNF.DCJITRFPFProyectoIPS.Cardinalidades.CeroMuchos
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.Cardinalidades/CeroMuchos.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		CeroMuchos = 2,
		/// <summary>
		/// UnoMuchos
		/// Description for DNF.DCJITRFPFProyectoIPS.Cardinalidades.UnoMuchos
		/// </summary>
		[DslDesign::DescriptionResource("DNF.DCJITRFPFProyectoIPS.Cardinalidades/UnoMuchos.Description", typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel), "DNF.DCJITRFPFProyectoIPS.GeneratedCode.DomainModelResx")]
		UnoMuchos = 3,
	}
}

