//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using System;
using System.Diagnostics;
using System.Drawing.Design;
using System.Windows.Forms;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;

namespace DNF.DCJITRFPFProyectoIPS
{
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	/// <remarks>
	/// Double-derived class to allow easier code customization.
	/// </remarks>
	public partial class DCJITRFPFProyectoIPSToolboxHelper : DCJITRFPFProyectoIPSToolboxHelperBase 
	{
		/// <summary>
		/// Constructs a new DCJITRFPFProyectoIPSToolboxHelper.
		/// </summary>
		public DCJITRFPFProyectoIPSToolboxHelper(global::System.IServiceProvider serviceProvider)
			: base(serviceProvider) { }
	}
	
	/// <summary>
	/// Helper class used to create and initialize toolbox items for this DSL.
	/// </summary>
	
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1001:TypesThatOwnDisposableFieldsShouldBeDisposable", Justification = "The store is disposed on domain shut down")]
	public abstract class DCJITRFPFProyectoIPSToolboxHelperBase
	{
		/// <summary>
		/// Toolbox item filter string used to identify DCJITRFPFProyectoIPS toolbox items.  
		/// </summary>
		/// <remarks>
		/// See the MSDN documentation for the ToolboxItemFilterAttribute class for more information on toolbox
		/// item filters.
		/// </remarks>
		public const string ToolboxFilterString = "DCJITRFPFProyectoIPS.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify EntidadAtributoConex connector tool.
		/// </summary>
		public const string EntidadAtributoConexFilterString = "EntidadAtributoConex.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify PrimeraRelacionTool connector tool.
		/// </summary>
		public const string PrimeraRelacionToolFilterString = "PrimeraRelacionTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify SegundaRelacionTool connector tool.
		/// </summary>
		public const string SegundaRelacionToolFilterString = "SegundaRelacionTool.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify RelacionAtributoConex connector tool.
		/// </summary>
		public const string RelacionAtributoConexFilterString = "RelacionAtributoConex.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify PagWebRefEntidad connector tool.
		/// </summary>
		public const string PagWebRefEntidadFilterString = "PagWebRefEntidad.1.0";
		/// <summary>
		/// Toolbox item filter string used to identify AtributoRefFormulario connector tool.
		/// </summary>
		public const string AtributoRefFormularioFilterString = "AtributoRefFormulario.1.0";

	
		private global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem> toolboxItemCache = new global::System.Collections.Generic.Dictionary<string, DslDesign::ModelingToolboxItem>();
		private DslModeling::Store toolboxStore;
		
		private global::System.IServiceProvider sp;
		
		/// <summary>
		/// Constructs a new DCJITRFPFProyectoIPSToolboxHelperBase.
		/// </summary>
		protected DCJITRFPFProyectoIPSToolboxHelperBase(global::System.IServiceProvider serviceProvider)
		{
			if(serviceProvider == null) throw new global::System.ArgumentNullException("serviceProvider");
			
			this.sp = serviceProvider;
		}
		
		/// <summary>
		/// Serivce provider used to access services from the hosting environment.
		/// </summary>
		protected global::System.IServiceProvider ServiceProvider
		{
			get
			{
				return this.sp;
			}
		}

		/// <summary>
		/// Returns the display name of the tab that should be opened by default when the editor is opened.
		/// </summary>
		public static string DefaultToolboxTabName
		{
			get
			{
				return global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel.SingletonResourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", global::System.Globalization.CultureInfo.CurrentUICulture);
			}
		}
		
		
		/// <summary>
		/// Returns the toolbox items count in the default tool box tab.
		/// </summary>
		public static int DefaultToolboxTabToolboxItemsCount
		{
			get
			{
				return 14;
			}
		}
		

		/// <summary>
		/// Returns a list of custom toolbox items to be added dynamically
		/// </summary>
		public virtual global::System.Collections.Generic.IList<DslDesign::ModelingToolboxItem> CreateToolboxItems()
		{
			global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem> toolboxItems = new global::System.Collections.Generic.List<DslDesign::ModelingToolboxItem>();
			return toolboxItems;
		}
		
		/// <summary>
		/// Creates an ElementGroupPrototype for the element tool corresponding to the given domain class id.
		/// Default behavior is to create a prototype containing an instance of the domain class.
		/// Derived classes may override this to add additional information to the prototype.
		/// </summary>
		protected virtual DslModeling::ElementGroupPrototype CreateElementToolPrototype(DslModeling::Store store, global::System.Guid domainClassId)
		{
			DslModeling::ModelElement element = store.ElementFactory.CreateElement(domainClassId);
			DslModeling::ElementGroup elementGroup = new DslModeling::ElementGroup(store.DefaultPartition);
			elementGroup.AddGraph(element, true);
			return elementGroup.CreatePrototype();
		}

		/// <summary>
		/// Returns instance of ModelingToolboxItem based on specified name.
		/// This method must be called from within a Transaction. Failure to do so will result in an exception
		/// </summary>
		/// <param name="itemId">unique name of desired ToolboxItem</param>
		/// <param name="store">Store to perform the operation against</param>
		/// <returns>An instance of ModelingToolboxItem if the itemId can be resolved, null otherwise</returns>
		public virtual DslDesign::ModelingToolboxItem GetToolboxItem(string itemId, DslModeling::Store store)
		{
			DslDesign::ModelingToolboxItem result = null;
			if (string.IsNullOrEmpty(itemId))
			{
				return null;
			}
			if (store == null)
			{
				return null;
			}
			global::System.Resources.ResourceManager resourceManager = global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;
			switch(itemId)
			{
				case "DNF.DCJITRFPFProyectoIPS.EntidadToolToolboxItem":
					// Add EntidadTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.EntidadToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						1, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EntidadToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EntidadToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EntidadTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EntidadToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DNF.DCJITRFPFProyectoIPS.Entidad.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.AtributoNMToolToolboxItem":
					// Add AtributoNMTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.AtributoNMToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						2, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AtributoNMToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AtributoNMToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AtributoNMTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AtributoNMToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DNF.DCJITRFPFProyectoIPS.AtributoNM.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.EntidadAtributoConexToolboxItem":

					// Add EntidadAtributoConex connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.EntidadAtributoConexToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						3, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("EntidadAtributoConexToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("EntidadAtributoConexToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"EntidadAtributoConex", // F1 help keyword for the toolbox item.
						resourceManager.GetString("EntidadAtributoConexToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(EntidadAtributoConexFilterString)
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.ClavePrimariaToolToolboxItem":
					// Add ClavePrimariaTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.ClavePrimariaToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						4, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("ClavePrimariaToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("ClavePrimariaToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"ClavePrimariaTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("ClavePrimariaToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DNF.DCJITRFPFProyectoIPS.ClavePrimaria.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.RelacionToolToolboxItem":
					// Add RelacionTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.RelacionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						5, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RelacionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RelacionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RelacionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RelacionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DNF.DCJITRFPFProyectoIPS.Relacion.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.PrimeraRelacionToolToolboxItem":

					// Add PrimeraRelacionTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.PrimeraRelacionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						6, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PrimeraRelacionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PrimeraRelacionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PrimeraRelacionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PrimeraRelacionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(PrimeraRelacionToolFilterString)
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.SegundaRelacionToolToolboxItem":

					// Add SegundaRelacionTool connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.SegundaRelacionToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						7, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("SegundaRelacionToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("SegundaRelacionToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"SegundaRelacionTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("SegundaRelacionToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(SegundaRelacionToolFilterString)
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.PortalWebToolToolboxItem":
					// Add PortalWebTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.PortalWebToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						8, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PortalWebToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PortalWebToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PortalWebTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PortalWebToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DNF.DCJITRFPFProyectoIPS.EstiloPortalWeb.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.PaginaWebToolToolboxItem":
					// Add PaginaWebTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.PaginaWebToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						9, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PaginaWebToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PaginaWebToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PaginaWebTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PaginaWebToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DNF.DCJITRFPFProyectoIPS.EstiloPaginaWeb.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.FormularioToolToolboxItem":
					// Add FormularioTool shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.FormularioToolToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						10, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("FormularioToolToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("FormularioToolToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"FormularioTool", // F1 help keyword for the toolbox item.
						resourceManager.GetString("FormularioToolToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DNF.DCJITRFPFProyectoIPS.EstiloFormulario.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.RelacionAtributoConexToolboxItem":

					// Add RelacionAtributoConex connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.RelacionAtributoConexToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						11, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("RelacionAtributoConexToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("RelacionAtributoConexToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"RelacionAtributoConex", // F1 help keyword for the toolbox item.
						resourceManager.GetString("RelacionAtributoConexToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(RelacionAtributoConexFilterString)
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.AtributoRelacionToolboxItem":
					// Add AtributoRelacion shape tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.AtributoRelacionToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						12, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AtributoRelacionToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AtributoRelacionToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AtributoRelacion", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AtributoRelacionToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						CreateElementToolPrototype(store, global::DNF.DCJITRFPFProyectoIPS.AtributoRelacion.DomainClassId), // ElementGroupPrototype (data object) representing model element on the toolbox.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
						new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require) 
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.PagWebRefEntidadToolboxItem":

					// Add PagWebRefEntidad connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.PagWebRefEntidadToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						13, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("PagWebRefEntidadToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("PagWebRefEntidadToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"PagWebRefEntidad", // F1 help keyword for the toolbox item.
						resourceManager.GetString("PagWebRefEntidadToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(PagWebRefEntidadFilterString)
						});
					break;
				case "DNF.DCJITRFPFProyectoIPS.AtributoRefFormularioToolboxItem":

					// Add AtributoRefFormulario connector tool.
					result = new DslDesign::ModelingToolboxItem(
						"DNF.DCJITRFPFProyectoIPS.AtributoRefFormularioToolboxItem", // Unique identifier (non-localized) for the toolbox item.
						14, // Position relative to other items in the same toolbox tab.
						resourceManager.GetString("AtributoRefFormularioToolboxItem", resourceCulture), // Localized display name for the item.
						(global::System.Drawing.Bitmap)DslDiagrams::ImageHelper.GetImage(resourceManager.GetObject("AtributoRefFormularioToolboxBitmap", resourceCulture)), // Image displayed next to the toolbox item.				
						"DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPS1ToolboxTab", // Unique identifier (non-localized) for the toolbox item tab.
						resourceManager.GetString("DCJITRFPFProyectoIPS1ToolboxTab", resourceCulture), // Localized display name for the toolbox tab.
						"AtributoRefFormulario", // F1 help keyword for the toolbox item.
						resourceManager.GetString("AtributoRefFormularioToolboxTooltip", resourceCulture), // Localized tooltip text for the toolbox item.
						null, // Connector toolbox items do not have an underlying data object.
						new global::System.ComponentModel.ToolboxItemFilterAttribute[] { // Collection of ToolboxItemFilterAttribute objects that determine visibility of the toolbox item.
							new global::System.ComponentModel.ToolboxItemFilterAttribute(ToolboxFilterString, global::System.ComponentModel.ToolboxItemFilterType.Require), 
							new global::System.ComponentModel.ToolboxItemFilterAttribute(AtributoRefFormularioFilterString)
						});
					break;
				default:
					break;
			} // end switch
			
			return result;
		}
		

		/// <summary>
		/// The store toe be used for all the toolbox item creation
		/// </summary>
		protected DslModeling::Store ToolboxStore
		{
			get
			{ 
				if (toolboxStore==null)
				{
					toolboxStore = new DslModeling::Store(this.ServiceProvider);
					EventHandler StoreCleanUp = (o, e) =>
					{
						//Since Store implements IDisposable, we need to dispose it when we're finished
						if (this.toolboxStore != null)
						{
							this.toolboxStore.Dispose();
						}
						this.toolboxStore = null;
					};
					//There is no DomainUnload event for the default AppDomain, so we listen for both ProcessExit and DomainUnload
					AppDomain.CurrentDomain.ProcessExit += new EventHandler(StoreCleanUp);
					AppDomain.CurrentDomain.DomainUnload += new EventHandler(StoreCleanUp);
					
					//load the domain model
					toolboxStore.LoadDomainModels(typeof(global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel));
					
				}
				return toolboxStore;
			}
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" returns the the toolbox item using cached dictionary
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve</param>
		private DslDesign::ModelingToolboxItem GetToolboxItem(string itemId)
		{
			DslDesign::ModelingToolboxItem item = null;

			if (!this.toolboxItemCache.TryGetValue(itemId, out item))
			{
				DslModeling::Store store = this.ToolboxStore;
				
				// Open transaction so we can create model elements corresponding to toolbox items.
				using (DslModeling::Transaction t = store.TransactionManager.BeginTransaction("CreateToolboxItems"))
				{
					// Retrieve the specified ToolboxItem from the DSL
					this.toolboxItemCache[itemId] = item = this.GetToolboxItem(itemId, store);
				}
			}

			return item;
		}
		
		/// <summary>
		/// Given a toolbox item "unique ID" and a data format identifier, returns the content of
		/// the data format. 
		/// </summary>
		/// <param name="itemId">The unique ToolboxItem to retrieve data for</param>
		/// <param name="format">The desired format of the resulting data</param>
		public virtual object GetToolboxItemData(string itemId, DataFormats.Format format)
		{
			DslDesign::ModelingToolboxItem item = null;

			global::System.Resources.ResourceManager resourceManager = global::DNF.DCJITRFPFProyectoIPS.DCJITRFPFProyectoIPSDomainModel.SingletonResourceManager;
			global::System.Globalization.CultureInfo resourceCulture = global::System.Globalization.CultureInfo.CurrentUICulture;

			System.Windows.Forms.IDataObject tbxDataObj;

			//get the toolbox item
			item = GetToolboxItem(itemId);

			if (item != null)
			{
				ToolboxItemContainer container = new ToolboxItemContainer(item);
				tbxDataObj = container.ToolboxData;

				if (tbxDataObj.GetDataPresent(format.Name))
				{
					return tbxDataObj.GetData(format.Name);
				}
				else 
				{
					string invalidFormatString = resourceManager.GetString("UnsupportedToolboxFormat", resourceCulture);
					throw new InvalidOperationException(string.Format(resourceCulture, invalidFormatString, format.Name));
				}
			}

			string errorFormatString = resourceManager.GetString("UnresolvedToolboxItem", resourceCulture);
			throw new InvalidOperationException(string.Format(resourceCulture, errorFormatString, itemId));
		}		
	}
}
