package upm.fis.practica.model.usuario;


import spark.Request;
import spark.Response;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Gesti�nGR
//  @ File Name : IUsuario.java
//  @ Date : 11/05/2022
//  @ Author : 
//
//
public interface IUsuario {
	public String getApellidos();
	
	public String getNombre();
	
	public String getCorreo();
	
	public String getDNI();
	
	public String getContrasenya();
	
	public void login();
	
	public void logout();




}
