
CREATE TABLE IF NOT EXISTS Pelicula(
Nombre VARCHAR(30),
PRIMARY KEY (Nombre)
);

CREATE TABLE IF NOT EXISTS Cine(
ID INTEGER,
Capacidad INTEGER NOT NULL,
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS Cliente(
ID INTEGER,
PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PeliculaVeCliente(
Nombre VARCHAR(30),
ID INTEGER,
FOREIGN KEY (Nombre) REFERENCES Pelicula(Nombre),
FOREIGN KEY (ID) REFERENCES Cliente(ID)
);

CREATE TABLE IF NOT EXISTS CineEstaPelicula(
ID INTEGER,
Nombre VARCHAR(30),
Sala INTEGER UNIQUE NOT NULL,
FOREIGN KEY (ID) REFERENCES Cine(ID),
FOREIGN KEY (Nombre) REFERENCES Pelicula(Nombre)
);


